# Image de base combinant .NET et Node.js
FROM mcr.microsoft.com/devcontainers/dotnet:1-9.0

# Installation supplémentaire si nécessaire (optionnel)
RUN apt-get update && apt-get install -y \
    git curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Vérification des versions installées
RUN node -v && npm -v && dotnet --version


# Définir le répertoire de travail
WORKDIR /workspaces
