# Utiliser l'image de base .NET
FROM mcr.microsoft.com/devcontainers/dotnet:1-9.0

# Installer Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm@11 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Vérifications (optionnel)
RUN dotnet --version && node -v && npm -v

# Définir le répertoire de travail
WORKDIR /workspaces
