/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProfile: typeof import('./components/Profile/AddProfile.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Image: typeof import('./components/utils/image.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideImage: typeof import('./components/utils/SiteImage.vue')['default']
    SideMenu: typeof import('./components/utils/SideMenu.vue')['default']
    SiteImage: typeof import('./components/utils/SiteImage.vue')['default']
    TableProfile: typeof import('./components/Profile/TableProfile.vue')['default']
    UpdateProfile: typeof import('./components/Profile/UpdateProfile.vue')['default']
  }
}
