name: CI Build Check

on:
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' 

      - name: Install dependencies
        run: dotnet restore ./workspaces/AutoDo/src/

      - name: Build project
        run: dotnet build --configuration Release --no-restore ./workspaces/AutoDo/src/

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal ./workspaces/AutoDo/src/
